<a href="https://colab.research.google.com/github/ancestor9/beat-master/blob/main/Data_mgt/01_Obtain_Data_Consumer_Behavior_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: 내 드라이브를 마운트(mount) 하라

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# prompt: /content/drive/MyDrive/data 에 데이터목록 확인하고 리스트에 담기

import os
data_list = []
for filename in os.listdir('/content/drive/MyDrive/data'):
    data_list.append(filename)
data_list

['2018년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2019년 소비자행태조사 원시데이터_답변.csv',
 '2019년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2018년 소비자행태조사 원시데이터_답변.csv',
 'merged_df.csv',
 'mapped_df.pkl',
 'processed_df.pkl',
 'df.pkl']

In [ ]:
# prompt: 2019년 소비자행태조사 원시데이터_답변.csv 읽어줘

import pandas as pd

# Assuming the CSV file is in your Google Drive's 'MyDrive/data' folder
file_path = '/content/drive/MyDrive/data/2019년 소비자행태조사 원시데이터_답변.csv'

try:
  # Read the CSV file into a pandas DataFrame
  df = pd.read_csv(file_path, encoding='cp949')  # Use cp949 encoding for Korean characters

  # Display the first few rows of the DataFrame
  print(df.head())

except FileNotFoundError:
  print(f"Error: File not found at {file_path}")
except Exception as e:
  print(f"An error occurred: {e}")

   癤풷EAR  A_001  A_002  A_003  A_004  A_006  A_007  A_009  A_011  A_013  ...  \
0   2019      1      1     14      1      6      6    NaN      1      8  ...
1   2019      1      1     14      1      6      6    NaN     99      8  ...
2   2019      1      1     14      1      6      6    NaN      1      8  ...
3   2019      1      1     14      1      6      8    NaN     99      8  ...
4   2019      1      1     14      1      6      9    NaN      1      8  ...

   K_05_015#1  K_05_015#2  K_05_015#3  K_05_015#4  K_05_015#5  K_05_015#6  \
0           3         NaN         NaN         NaN         NaN         NaN
1           3         NaN         NaN         NaN         NaN         NaN
2           3         6.0         7.0         NaN         NaN         NaN
3           3         4.0         NaN         NaN         NaN         NaN
4           3         NaN         NaN         NaN         NaN         NaN

   K_05_015#7  K_05_015#8  K_05_015#9  K_05_015#10
0         NaN         NaN         NaN          NaN
1         NaN         NaN         NaN          NaN
2         NaN         NaN         NaN          NaN
3         NaN         NaN         NaN          NaN
4         NaN         NaN         NaN          NaN

[5 rows x 3624 columns]

In [ ]:
df

,癤풷EAR,A_001,A_002,A_003,A_004,A_006,A_007,A_009,A_011,A_013,...,K_05_015#1,K_05_015#2,K_05_015#3,K_05_015#4,K_05_015#5,K_05_015#6,K_05_015#7,K_05_015#8,K_05_015#9,K_05_015#10
0,2019,1,1,14,1,6,6,NaN,1,8,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,1,1,14,1,6,6,NaN,99,8,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,1,1,14,1,6,6,NaN,1,8,...,3,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,1,1,14,1,6,8,NaN,99,8,...,3,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,1,1,14,1,6,9,NaN,1,8,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2019,2,5,58,4,4,1,1.0,1,3,...,1,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3996,2019,2,6,63,4,5,7,NaN,4,4,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,2019,2,6,61,4,4,4,2.0,1,3,...,1,3.0,4.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
3998,2019,2,6,67,4,4,2,2.0,1,3,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,2019,2,6,65,4,5,4,NaN,2,4,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# prompt: /content/drive/MyDrive/data 에 데이터목록 확인하고 리스트에 담기

import os

data_list = []
for filename in os.listdir('/content/drive/MyDrive/data'):
    data_list.append(filename)
data_list

['2018년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2019년 소비자행태조사 원시데이터_답변.csv',
 '2019년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2018년 소비자행태조사 원시데이터_답변.csv']

In [ ]:
import pandas as pd
df_2019_view = pd.read_excel('/content/drive/MyDrive/data/2019년 소비자행태조사 원시데이터_문항,보기.xlsx')
df_2019_view

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,항목ID,항목명,항목분류,항목유형,항목설명
0,YEAR,조사년도,DEMO,단수,<없음>
1,A_001,성별,DEMO,단수,귀하의 성별은 무엇입니까?
2,A_002,연령(10대),DEMO,단수,귀하의 연령은 무엇입니까?
3,A_003,연령(1세),DEMO,주관식,귀하의 연령은 무엇입니까?
4,A_004,지역(권역),DEMO,단수,현재 거주하고 계신 지역은 어디인가요?
...,...,...,...,...,...
3618,K_05_015#6,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3619,K_05_015#7,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3620,K_05_015#8,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3621,K_05_015#9,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3622,K_05_015#10,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....

In [ ]:
df_2018_view = pd.read_excel('/content/drive/MyDrive/data/2018년 소비자행태조사 원시데이터_문항,보기.xlsx')
df_2018_view

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,항목ID,항목명,항목분류,항목유형,항목설명
0,YEAR,조사년도,DEMO,단수,<없음>
1,A_001,성별,DEMO,단수,귀하의 성별은 무엇입니까?
2,A_002,연령(10대),DEMO,단수,귀하의 연령은 무엇입니까?
3,A_003,연령(1세),DEMO,주관식,귀하의 연령은 무엇입니까?
4,A_004,지역(권역),DEMO,단수,현재 거주하고 계신 지역은 어디인가요?
...,...,...,...,...,...
3532,K_05_015#6,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3533,K_05_015#7,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3534,K_05_015#8,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3535,K_05_015#9,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3536,K_05_015#10,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....

## [도장깨기](https://github.com/ancestor9/beat-master) 에서 필요한 코드 가져오기

In [ ]:
import numpy as np
selected_col = ([1, 3, 4, 5, 6, 9, 11, 14, 16] + list(np.arange(44,50)) +
                list(np.arange(293,305)) + list(np.arange(311,321)) + [379])
selected_col

[1,
 3,
 4,
 5,
 6,
 9,
 11,
 14,
 16,
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(293),
 np.int64(294),
 np.int64(295),
 np.int64(296),
 np.int64(297),
 np.int64(298),
 np.int64(299),
 np.int64(300),
 np.int64(301),
 np.int64(302),
 np.int64(303),
 np.int64(304),
 np.int64(311),
 np.int64(312),
 np.int64(313),
 np.int64(314),
 np.int64(315),
 np.int64(316),
 np.int64(317),
 np.int64(318),
 np.int64(319),
 np.int64(320),
 379]

In [ ]:
file_path  = '/content/drive/MyDrive/data/' + data_list[1]
file_path

'/content/drive/MyDrive/data/2019년 소비자행태조사 원시데이터_답변.csv'

In [ ]:
%time df_2019 = pd.read_csv(file_path, usecols= selected_col)

CPU times: user 228 ms, sys: 23.6 ms, total: 251 ms
Wall time: 1.03 s

In [ ]:
df_2019

,A_001,A_003,A_004,A_006,A_007,A_013,A_016,A_019,A_027,B_03_026,...,C_01_003#2,C_01_003#3,C_01_003#4,C_01_003#5,C_01_003#6,C_01_003#7,C_01_003#8,C_01_003#9,C_01_003#10,C_01_033
0,1,14,1,6,6,8,3,2,NaN,0.0,...,9.0,10.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,2
1,1,14,1,6,6,8,1,2,NaN,30.0,...,6.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,1,14,1,6,6,8,2,2,NaN,90.0,...,4.0,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1,14,1,6,8,8,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4,1,14,1,6,9,8,1,2,NaN,0.0,...,5.0,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2,58,4,4,1,3,1,3,2.0,NaN,...,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3996,2,63,4,5,7,4,1,1,2.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3997,2,61,4,4,4,3,2,1,1.0,NaN,...,4.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2
3998,2,67,4,4,2,3,1,3,2.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3999,2,65,4,5,4,4,1,1,3.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [ ]:
df_2019.columns

Index(['A_001', 'A_003', 'A_004', 'A_006', 'A_007', 'A_013', 'A_016', 'A_019',
       'A_027', 'B_03_026', 'B_03_027', 'B_03_028', 'B_03_029', 'B_03_030',
       'B_03_031', 'C_01_001#1', 'C_01_001#2', 'C_01_001#3', 'C_01_001#4',
       'C_01_001#5', 'C_01_001#6', 'C_01_001#7', 'C_01_001#8', 'C_01_001#9',
       'C_01_001#10', 'C_01_001#11', 'C_01_001#12', 'C_01_003#1', 'C_01_003#2',
       'C_01_003#3', 'C_01_003#4', 'C_01_003#5', 'C_01_003#6', 'C_01_003#7',
       'C_01_003#8', 'C_01_003#9', 'C_01_003#10', 'C_01_033'],
      dtype='object')

In [ ]:
# 2018년도 데이터도 동일하게 추출하기

df_2019.columns.to_list()

['A_001',
 'A_003',
 'A_004',
 'A_006',
 'A_007',
 'A_013',
 'A_016',
 'A_019',
 'A_027',
 'B_03_026',
 'B_03_027',
 'B_03_028',
 'B_03_029',
 'B_03_030',
 'B_03_031',
 'C_01_001#1',
 'C_01_001#2',
 'C_01_001#3',
 'C_01_001#4',
 'C_01_001#5',
 'C_01_001#6',
 'C_01_001#7',
 'C_01_001#8',
 'C_01_001#9',
 'C_01_001#10',
 'C_01_001#11',
 'C_01_001#12',
 'C_01_003#1',
 'C_01_003#2',
 'C_01_003#3',
 'C_01_003#4',
 'C_01_003#5',
 'C_01_003#6',
 'C_01_003#7',
 'C_01_003#8',
 'C_01_003#9',
 'C_01_003#10',
 'C_01_033']

In [ ]:
file_path  = '/content/drive/MyDrive/data/' + data_list[3]
file_path

'/content/drive/MyDrive/data/2018년 소비자행태조사 원시데이터_답변.csv'

In [ ]:
%time df_2018 = pd.read_csv(file_path, usecols= selected_col)
df_2018

CPU times: user 331 ms, sys: 24 ms, total: 354 ms
Wall time: 929 ms

,A_001,A_003,A_004,A_006,A_007,A_013,A_016,A_019,A_027,B_03_027,...,C_01_003#3,C_01_003#4,C_01_003#5,C_01_003#6,C_01_003#7,C_01_003#8,C_01_003#9,C_01_003#10,C_01_003#11,C_01_031#1
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,1,14,1,6,8,8,1,2,NaN,NaN,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,1,14,1,6,6,8,1,2,NaN,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,1,14,1,6,8,8,2,2,NaN,90.0,...,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,NaN,2
4,1,14,1,6,6,8,1,2,NaN,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2,51,4,3,3,4,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3996,2,57,4,4,5,4,1,1,2.0,NaN,...,4.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3997,2,57,4,5,4,3,1,1,2.0,NaN,...,6.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3998,2,60,4,5,2,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3999,2,65,4,5,2,4,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6

In [ ]:
# prompt: df_2018 과 df_2019의 컬럼이 동일한가?

# Check if columns of df_2018 and df_2019 are the same
columns_2018 = df_2018.columns.tolist()
columns_2019 = df_2019.columns.tolist()

if columns_2018 == columns_2019:
  print("The columns of df_2018 and df_2019 are identical.")
else:
  print("The columns of df_2018 and df_2019 are different.")

  # Find the different columns
  diff_2018 = list(set(columns_2018) - set(columns_2019))
  diff_2019 = list(set(columns_2019) - set(columns_2018))

  print("Columns present in df_2018 but not in df_2019:", diff_2018)
  print("Columns present in df_2019 but not in df_2018:", diff_2019)

The columns of df_2018 and df_2019 are different.
Columns present in df_2018 but not in df_2019: ['C_01_001#13', 'B_03_032', 'C_01_003#11', 'C_01_031#1']
Columns present in df_2019 but not in df_2018: ['C_01_003#1', 'C_01_033', 'C_01_001#1', 'B_03_026']

## **<font color='red'> 앗 !**

In [ ]:
# prompt: df_2019.columns.to_list() 컬럼만 file_path에서 추출하려 데이터프레임으로 읽는다. try except 문장은 생략해줘
file_path  = '/content/drive/MyDrive/data/' + data_list[3]
df_2018 = pd.read_csv(file_path, usecols=df_2019.columns.to_list())
df_2018

,A_001,A_003,A_004,A_006,A_007,A_013,A_016,A_019,A_027,B_03_026,...,C_01_003#2,C_01_003#3,C_01_003#4,C_01_003#5,C_01_003#6,C_01_003#7,C_01_003#8,C_01_003#9,C_01_003#10,C_01_033
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,14,1,6,8,8,1,2,NaN,NaN,...,6.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1,14,1,6,8,8,2,2,NaN,90.0,...,4.0,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2,51,4,3,3,4,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3996,2,57,4,4,5,4,1,1,2.0,NaN,...,6.0,4.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3997,2,57,4,5,4,3,1,1,2.0,NaN,...,5.0,6.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,2
3998,2,60,4,5,2,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3999,2,65,4,5,2,4,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [ ]:
columns_2018 = df_2018.columns.tolist()
columns_2019 = df_2019.columns.tolist()

if columns_2018 == columns_2019:
  print("The columns of df_2018 and df_2019 are identical.")

The columns of df_2018 and df_2019 are identical.

### Good !

In [ ]:
pd.concat([df_2018, df_2019])

,A_001,A_003,A_004,A_006,A_007,A_013,A_016,A_019,A_027,B_03_026,...,C_01_003#2,C_01_003#3,C_01_003#4,C_01_003#5,C_01_003#6,C_01_003#7,C_01_003#8,C_01_003#9,C_01_003#10,C_01_033
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,14,1,6,8,8,1,2,NaN,NaN,...,6.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1,14,1,6,8,8,2,2,NaN,90.0,...,4.0,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2,58,4,4,1,3,1,3,2.0,NaN,...,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3996,2,63,4,5,7,4,1,1,2.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3997,2,61,4,4,4,3,2,1,1.0,NaN,...,4.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2
3998,2,67,4,4,2,3,1,3,2.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3999,2,65,4,5,4,4,1,1,3.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [ ]:
# prompt: df_2018, df_2019 데이터를 merge 해줘. 단 df_2018과 df_2019 데이터프레임의 컬럼에 년도를 각각 2018과 2019로 만든후에 합쳐줘

import pandas as pd
# Add year columns to the dataframes
df_2018['year'] = 2018
df_2019['year'] = 2019

# Concatenate the dataframes
df = pd.concat([df_2018, df_2019], ignore_index=True)

df

,A_001,A_003,A_004,A_006,A_007,A_013,A_016,A_019,A_027,B_03_026,...,C_01_003#3,C_01_003#4,C_01_003#5,C_01_003#6,C_01_003#7,C_01_003#8,C_01_003#9,C_01_003#10,C_01_033,year
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2018
1,1,14,1,6,8,8,1,2,NaN,NaN,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
3,1,14,1,6,8,8,2,2,NaN,90.0,...,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1,2018
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2,58,4,4,1,3,1,3,2.0,NaN,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2019
7996,2,63,4,5,7,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7997,2,61,4,4,4,3,2,1,1.0,NaN,...,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7998,2,67,4,4,2,3,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7999,2,65,4,5,4,4,1,1,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019

In [ ]:
df_2018_view

,항목ID,항목명,항목분류,항목유형,항목설명
0,YEAR,조사년도,DEMO,단수,<없음>
1,A_001,성별,DEMO,단수,귀하의 성별은 무엇입니까?
2,A_002,연령(10대),DEMO,단수,귀하의 연령은 무엇입니까?
3,A_003,연령(1세),DEMO,주관식,귀하의 연령은 무엇입니까?
4,A_004,지역(권역),DEMO,단수,현재 거주하고 계신 지역은 어디인가요?
...,...,...,...,...,...
3532,K_05_015#6,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3533,K_05_015#7,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3534,K_05_015#8,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3535,K_05_015#9,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....
3536,K_05_015#10,평소 즐겨 보는 뉴스 및 콘텐츠,기타>나쁜광고,복수,귀하께서 평소 자주 보거나 즐겨 이용하는 뉴스(또는 콘텐츠)를 모두 선택해주십시오....

In [ ]:
# prompt: df.columns에 해당되는 변수만 df_2018_view의 항목ID에서 추출하라

# Extract columns from df_2018_view that are present in df.columns
df_2018_view_subset = df_2018_view[df_2018_view['항목ID'].isin(df.columns)]
df_2018_view_subset

,항목ID,항목명,항목분류,항목유형,항목설명
1,A_001,성별,DEMO,단수,귀하의 성별은 무엇입니까?
3,A_003,연령(1세),DEMO,주관식,귀하의 연령은 무엇입니까?
4,A_004,지역(권역),DEMO,단수,현재 거주하고 계신 지역은 어디인가요?
5,A_006,직업,DEMO,단수,귀하의 직업은 무엇입니까?
6,A_007,가구 월평균 소득(1),DEMO,단수,귀댁의 월평균 소득은 얼마나 됩니까?
9,A_013,최종학력,DEMO,단수,귀하의 최종 학력은 어떻게 되십니까?
11,A_016,주거 형태,DEMO,단수,귀댁은 다음 중 어떤 형태로 살고 계십니까?
14,A_019,결혼 여부,DEMO,단수,귀하는 현재 결혼을 하셨습니까?
16,A_027,자녀 총 수,DEMO,단수,귀하의 자녀는 다음 연령대(나이는 만 나이 기준)에 모두 몇 명입니까? - 총 수
43,B_03_026,평일 인터넷 이용시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 평일에 평균 몇 분 정도 PC(데스크탑/노트북)을 통해 인터넷을 이용하십니까?
44,B_03_027,토요일 인터넷 이용시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 토요일에 몇 분 정도 PC(데스크탑/노트북)을 통해 인터넷을 이용하십니까?
45,B_03_028,일요일 인터넷 이용시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 일요일에 몇 분 정도 PC(데스크탑/노트북)을 통해 인터넷을 이용하십니까?
46,B_03_029,평일 하루 평균 모바일 인터넷 이용 시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 평일 평균 몇 분 정도 모바일(스마트폰/태블릿PC)을 통해 인터넷을 이용...
47,B_03_030,토요일 하루 평균 모바일 인터넷 이용 시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 토요일 평균 몇 분 정도 모바일(스마트폰/태블릿PC)을 통해 인터넷을 이...
48,B_03_031,일요일 하루 평균 모바일 인터넷 이용 시간(분),전반적 매체이용행태>매체 이용시간,주관식,귀하께서는 일요일 평균 몇 분 정도 모바일(스마트폰/태블릿PC)을 통해 인터넷을 이...
292,C_01_001#1,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
293,C_01_001#2,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
294,C_01_001#3,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
295,C_01_001#4,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
296,C_01_001#5,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
297,C_01_001#6,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
298,C_01_001#7,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
299,C_01_001#8,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
300,C_01_001#9,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
301,C_01_001#10,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
302,C_01_001#11,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
303,C_01_001#12,즐겨 보는 TV 프로그램 장르,매체이용행태>TV종합,복수,귀하께서 즐겨보시는 TV 프로그램 장르를 모두 체크해 주십시오
310,C_01_003#1,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
311,C_01_003#2,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
312,C_01_003#3,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
313,C_01_003#4,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
314,C_01_003#5,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
315,C_01_003#6,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
316,C_01_003#7,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
317,C_01_003#8,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
318,C_01_003#9,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
319,C_01_003#10,TV 시청 시 즐겨 보는 국내 드라마 장르,매체이용행태>TV종합,복수,TV 시청 시 즐겨보는 드라마 장르를 모두 체크해 주십시오.
401,C_01_033,PPL 제품/서비스/장소 실제 구입/이용 여부,매체이용행태>TV종합,단수,TV 프로그램에서 PPL로 본 후 해당 제품/서비스(장소포함)를 실제로 구입/이용한...

In [ ]:
# prompt: df_2018_view_subset, 항목ID와 항목명만 사전혀응로 추출

# Create a dictionary from the subset
item_dict = dict(zip(df_2018_view_subset['항목ID'], df_2018_view_subset['항목명']))
item_dict

{'A_001': '성별',
 'A_003': '연령(1세)',
 'A_004': '지역(권역)',
 'A_006': '직업',
 'A_007': '가구 월평균 소득(1)',
 'A_013': '최종학력',
 'A_016': '주거 형태',
 'A_019': '결혼 여부',
 'A_027': '자녀 총 수',
 'B_03_026': '평일 인터넷 이용시간(분)',
 'B_03_027': '토요일 인터넷 이용시간(분)',
 'B_03_028': '일요일 인터넷 이용시간(분)',
 'B_03_029': '평일 하루 평균 모바일 인터넷 이용 시간(분)',
 'B_03_030': '토요일 하루 평균 모바일 인터넷 이용 시간(분)',
 'B_03_031': '일요일 하루 평균 모바일 인터넷 이용 시간(분)',
 'C_01_001#1': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#2': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#3': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#4': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#5': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#6': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#7': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#8': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#9': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#10': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#11': '즐겨 보는 TV 프로그램 장르',
 'C_01_001#12': '즐겨 보는 TV 프로그램 장르',
 'C_01_003#1': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#2': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#3': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#4': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#5': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#6': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#7': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#8': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#9': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_003#10': 'TV 시청 시 즐겨 보는 국내 드라마 장르 ',
 'C_01_033': 'PPL 제품/서비스/장소 실제 구입/이용 여부'}

In [ ]:
item_dict = {
    'A_001': '성별',
    'A_003': '연령',
    'A_004': '지역',
    'A_006': '직업',
    'A_007': '소득',
    'A_013': '학력',
    'A_016': '주거형태',
    'A_019': '결혼여부',
    'A_027': '자녀수',
    'B_03_026': '평일인터넷',
    'B_03_027': '토요일인터넷',
    'B_03_028': '일요일인터넷',
    'B_03_029': '평일모바일',
    'B_03_030': '토요일모바일',
    'B_03_031': '일요일모바일',
    'C_01_001#1': 'TV장르1',
    'C_01_001#2': 'TV장르2',
    'C_01_001#3': 'TV장르3',
    'C_01_001#4': 'TV장르4',
    'C_01_001#5': 'TV장르5',
    'C_01_001#6': 'TV장르6',
    'C_01_001#7': 'TV장르7',
    'C_01_001#8': 'TV장르8',
    'C_01_001#9': 'TV장르9',
    'C_01_001#10': 'TV장르10',
    'C_01_001#11': 'TV장르11',
    'C_01_001#12': 'TV장르12',
    'C_01_003#1': '국드장르1',
    'C_01_003#2': '국드장르2',
    'C_01_003#3': '국드장르3',
    'C_01_003#4': '국드장르4',
    'C_01_003#5': '국드장르5',
    'C_01_003#6': '국드장르6',
    'C_01_003#7': '국드장르7',
    'C_01_003#8': '국드장르8',
    'C_01_003#9': '국드장르9',
    'C_01_003#10': '국드장르10',
    'C_01_033': 'PPL구입여부'
}

In [ ]:
# prompt: df의 컬럼명을 item_dict로 mapping하기

# Rename columns of df using item_dict
df= df.rename(columns=item_dict)
df

,성별,연령,지역,직업,소득,학력,주거형태,결혼여부,자녀수,평일인터넷,...,국드장르3,국드장르4,국드장르5,국드장르6,국드장르7,국드장르8,국드장르9,국드장르10,PPL구입여부,year
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2018
1,1,14,1,6,8,8,1,2,NaN,NaN,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
3,1,14,1,6,8,8,2,2,NaN,90.0,...,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1,2018
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2,58,4,4,1,3,1,3,2.0,NaN,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2019
7996,2,63,4,5,7,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7997,2,61,4,4,4,3,2,1,1.0,NaN,...,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7998,2,67,4,4,2,3,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7999,2,65,4,5,4,4,1,1,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019

In [ ]:
data_list

['2018년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2019년 소비자행태조사 원시데이터_답변.csv',
 '2019년 소비자행태조사 원시데이터_문항,보기.xlsx',
 '2018년 소비자행태조사 원시데이터_답변.csv']

In [ ]:
# prompt: '2018년 소비자행태조사 원시데이터_문항,보기.xlsx'의 파일을 읽어서 두번쨰 시트를 확인하기, try 문장제거
df_second_sheet = pd.read_excel('/content/drive/MyDrive/data/2018년 소비자행태조사 원시데이터_문항,보기.xlsx', sheet_name=1)
df_second_sheet # Print the first few rows of the second sheet

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

              항목ID  항목코드  항목코드명
0             YEAR  2001  2001년
1             YEAR  2002  2002년
2             YEAR  2003  2003년
3             YEAR  2004  2004년
4             YEAR  2005  2005년
...            ...   ...    ...
54879  K_05_015#10    12     날씨
54880  K_05_015#10    13     음악
54881  K_05_015#10    14     여행
54882  K_05_015#10    15   E스포츠
54883  K_05_015#10    99     없다

[54884 rows x 3 columns]

In [ ]:
item_dict

{'A_001': '성별',
 'A_003': '연령',
 'A_004': '지역',
 'A_006': '직업',
 'A_007': '소득',
 'A_013': '학력',
 'A_016': '주거형태',
 'A_019': '결혼여부',
 'A_027': '자녀수',
 'B_03_026': '평일인터넷',
 'B_03_027': '토요일인터넷',
 'B_03_028': '일요일인터넷',
 'B_03_029': '평일모바일',
 'B_03_030': '토요일모바일',
 'B_03_031': '일요일모바일',
 'C_01_001#1': 'TV장르1',
 'C_01_001#2': 'TV장르2',
 'C_01_001#3': 'TV장르3',
 'C_01_001#4': 'TV장르4',
 'C_01_001#5': 'TV장르5',
 'C_01_001#6': 'TV장르6',
 'C_01_001#7': 'TV장르7',
 'C_01_001#8': 'TV장르8',
 'C_01_001#9': 'TV장르9',
 'C_01_001#10': 'TV장르10',
 'C_01_001#11': 'TV장르11',
 'C_01_001#12': 'TV장르12',
 'C_01_003#1': '국드장르1',
 'C_01_003#2': '국드장르2',
 'C_01_003#3': '국드장르3',
 'C_01_003#4': '국드장르4',
 'C_01_003#5': '국드장르5',
 'C_01_003#6': '국드장르6',
 'C_01_003#7': '국드장르7',
 'C_01_003#8': '국드장르8',
 'C_01_003#9': '국드장르9',
 'C_01_003#10': '국드장르10',
 'C_01_033': 'PPL구입여부'}

In [ ]:
# prompt: item_dict의 key만 추출하여 df_second_sheet의 '항목ID'dhk mapping하고 해당되는 값은 '항목코드' 커럼의 값을 갖는 데이터 구종를 만들어줘

# Create a new DataFrame with '항목ID' and '항목코드' columns
df_mapping = pd.DataFrame({'항목ID': item_dict.keys(), '항목코드': item_dict.values()})

# Merge df_mapping with df_second_sheet based on '항목ID'
merged_df = pd.merge(df_second_sheet, df_mapping, on='항목ID', how='inner')

# Display the resulting DataFrame
merged_df

            항목ID  항목코드_x           항목코드명   항목코드_y
0          A_001       1               남       성별
1          A_001       2               여       성별
2          A_004       1              서울       지역
3          A_004       2           경기/인천       지역
4          A_004       3        대전/충청/세종       지역
..           ...     ...             ...      ...
486  C_01_003#10      21             복수극   국드장르10
487  C_01_003#10      22              기타   국드장르10
488  C_01_003#10      23  특별히 즐겨보는 장르 없음   국드장르10
489     C_01_033       1              있다  PPL구입여부
490     C_01_033       2              없다  PPL구입여부

[491 rows x 4 columns]

In [ ]:
df['국드장르10'].unique()

array([nan, 14., 19., 21., 18., 20., 17., 13., 16., 12., 15., 11., 10.])

In [ ]:
df

,성별,연령,지역,직업,소득,학력,주거형태,결혼여부,자녀수,평일인터넷,...,국드장르3,국드장르4,국드장르5,국드장르6,국드장르7,국드장르8,국드장르9,국드장르10,PPL구입여부,year
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2018
1,1,14,1,6,8,8,1,2,NaN,NaN,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
3,1,14,1,6,8,8,2,2,NaN,90.0,...,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1,2018
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2,58,4,4,1,3,1,3,2.0,NaN,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2019
7996,2,63,4,5,7,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7997,2,61,4,4,4,3,2,1,1.0,NaN,...,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7998,2,67,4,4,2,3,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7999,2,65,4,5,4,4,1,1,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019

In [ ]:
# prompt: df와 merged_df를 /content/drive/MyDrive/data에 pkl파일과 csv 파일로 저장해다오

# Save df as pickle and csv
df.to_pickle('/content/drive/MyDrive/data/df.pkl')

# Save merged_df as pickle and csv
merged_df.to_csv('/content/drive/MyDrive/data/merged_df.csv', index=False)

In [ ]:
# prompt: /content/drive/MyDrive/data/df.pkl 을 읽어줘
%time df = pd.read_pickle('/content/drive/MyDrive/data/df.pkl')
df

CPU times: user 4.15 ms, sys: 2.01 ms, total: 6.16 ms
Wall time: 20.3 ms

,성별,연령,지역,직업,소득,학력,주거형태,결혼여부,자녀수,평일인터넷,...,국드장르3,국드장르4,국드장르5,국드장르6,국드장르7,국드장르8,국드장르9,국드장르10,PPL구입여부,year
0,1,14,1,6,6,8,1,2,NaN,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2018
1,1,14,1,6,8,8,1,2,NaN,NaN,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
2,1,14,1,6,6,8,1,2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
3,1,14,1,6,8,8,2,2,NaN,90.0,...,7.0,9.0,11.0,12.0,13.0,14.0,NaN,NaN,1,2018
4,1,14,1,6,6,8,1,2,NaN,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2,58,4,4,1,3,1,3,2.0,NaN,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2019
7996,2,63,4,5,7,4,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7997,2,61,4,4,4,3,2,1,1.0,NaN,...,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7998,2,67,4,4,2,3,1,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
7999,2,65,4,5,4,4,1,1,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2019

### **데이터프레임의 값의 의미는?**

In [ ]:
df['성별'].sample(5)

5926    1
885     2
6726    2
5928    1
768     2
Name: 성별, dtype: int64

In [ ]:
merged_df[merged_df['항목코드_y'] == '성별']

    항목ID  항목코드_x 항목코드명 항목코드_y
0  A_001       1     남     성별
1  A_001       2     여     성별

In [ ]:
# prompt: merged_df[merged_df['항목코드_y'] == '성별']의 항목코드_x, 항목코드명 사전형으로 만들어라

# Create the dictionary
gender_dict = dict(zip(merged_df[merged_df['항목코드_y'] == '성별']['항목코드_x'],
                       merged_df[merged_df['항목코드_y'] == '성별']['항목코드명']))

gender_dict

{1: '남', 2: '여'}

In [ ]:
# prompt: df['성별']의 값을 gender_dict와 mapping하라

# Apply the mapping to the '성별' column
df['성별'].map(gender_dict)

0       남
1       남
2       남
3       남
4       남
       ..
7995    여
7996    여
7997    여
7998    여
7999    여
Name: 성별, Length: 8000, dtype: object

In [ ]:
# prompt: df['성별'].map(gender_dict) 값의 빈도를 나타내어라

# Calculate the frequency of values in the '성별' column after mapping
gender_frequency = df['성별'].map(gender_dict).value_counts()

gender_frequency

성별
남    4035
여    3965
Name: count, dtype: int64

In [ ]:
# prompt: df['성별'].map(gender_dict) 값의 빈도의 비중을 나타내어라

# Calculate the proportion of each gender
gender_proportion = df['성별'].map(gender_dict).value_counts(normalize=True)

gender_proportion

성별
남    0.504375
여    0.495625
Name: proportion, dtype: float64